name: generate Statistics

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: config for git
        run: |
          git config user.email "<>"
          git config user.name "Statistik Bot"

      - name: compute
        run: |
          ./.github/stats.sh

      - name: push stats
        run: |
          git add docs/STATS.md
          git commit -m "[Statistik Bot] tägliches Update der STATS.md"
          git push origin
