name: generate Statistics

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            docs
          fetch-depth: 0

      - name: config for git
        run: |
          git config user.email "<>"
          git config user.name "Statistik Bot"

      - name: compute
        run: |
          ./.github/resources/stats.sh
          cat docs/STATS.md

      - name: push stats
        run: |
          if [[ "$(git log -1 --pretty=%B)" != "[Statistik Bot]"* ]]; then
            git add docs/STATS.md
            git commit -m "[Statistik Bot] update of STATS.md"
            git push origin
          fi
