name: test code

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      ignoreLock:
        description: 'Ignore flake.lock'
        required: false
        default: false
        type: boolean

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: delete Lockfile
        if: ${{ inputs.ignoreLock }}
        run: rm flake.lock

      - name: execute tests
        run: nix develop -c check